### ISSUE TITLE
branch property defn

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-invite-schema#1]
branch can be either : 
  - a single MsgId
  - an array of MsgIds

I think ? This would be an ideal thing to collect into `ssb-schema-definitions` !

cc @KGibb8

**Comment by dominictarr** [comment]
correct.

**Comment by m4gpi** [comment]
Didn't know `branch` could be many! Nice :+1: 

Agreed, hadn't looked at this since separating the schema definitions into a separate repo.
